
// This file was auto-generated by ML.NET Model Builder. 

using AVACore_Predict;

// Create single instance of sample data from first line of dataset for model input
AVACore.ModelInput sampleData = new AVACore.ModelInput()
{
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Month with predicted Month from sample data...\n\n");


Console.WriteLine($"Month: {@"2-Jan"}");


var sortedScoresWithLabel = AVACore.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

